import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const iconsDirectory = path.join(projectRoot, 'src/assets/icons');
const registryFile = path.join(projectRoot, 'src/components/generated/IconRegistry.ts');

function extractIconBody(svg, file) {
	const match = svg.match(/<svg\b[^>]*>([\s\S]*)<\/svg>\s*$/i);
	if (!match) {
		throw new Error(`Icon file must contain a complete SVG document: ${file}`);
	}

	return match[1].trim();
}

export async function generateIconRegistry() {
	const files = (await readdir(iconsDirectory))
		.filter((file) => file.endsWith('.svg'))
		.sort((left, right) => left.localeCompare(right));

	const icons = await Promise.all(
		files.map(async (file) => ({
			name: file.slice(0, -'.svg'.length),
			body: extractIconBody(await readFile(path.join(iconsDirectory, file), 'utf8'), file),
		})),
	);

	const output = [
		'// This file is generated by scripts/generate-icons.mjs. Do not edit manually.',
		'',
		'export const iconPaths = {',
		...icons.map(({ name, body }) => `\t${JSON.stringify(name)}: ${JSON.stringify(body)},`),
		'} as const;',
		'',
		'export type IconName = keyof typeof iconPaths;',
		'',
	].join('\n');

	await mkdir(path.dirname(registryFile), { recursive: true });
	const current = await readFile(registryFile, 'utf8').catch(() => null);
	if (current !== output) {
		await writeFile(registryFile, output);
	}
}

